version: '3'
services:
  mysqldb:
    image: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: grantsAndLoans
    volumes: 
      - db-config:/etc/mysql
      - db-data:/var/lib/mysql
      - ./db/backup/files/:/data_backup/data

  nest-app:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: node-mysql-app
    ports:
      - 3000:3000
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - mysqldb
    stdin_open: true
    tty: true


volumes: 
  db-config:
  db-data:
